fallback-grpc-addr: 0.0.0.0:3030
dial-grpc-timeout: 100

jaeger:
  url: "http://127.0.0.1:14268/api/traces"

consul:
  addr: 127.0.0.1:8500

order:
  service-name: order
  server-to-run: http
  http-addr: 10.11.69.39:8282
  grpc-addr: 10.11.69.39:5002

stock:
  service-name: stock
  server-to-run: grpc
  http-addr: 10.11.69.39:8283
  grpc-addr: 10.11.69.39:5003

payment:
  service-name: payment
  server-to-run: http
  http-addr: 10.11.69.39:8284
  grpc-addr: 10.11.69.39:5004

rabbitmq:
  user: guest
  password: guest
  host: 127.0.0.1
  port: 5672

max-retry: 3

mongo:
  user: root
  password: password
  host: 127.0.0.1
  port: 27017
  db-name: "order"
  coll-name: "order"

mysql:
  user: root
  password: root
  host: localhost
  port: 3307
  dbname: "gorder"


stripe-key: "${STRIPE_KEY}"
endpoint-stripe-secret: "${ENDPOINT_STRIPE_SECRET}"
